#!/usr/bin/env node
/**
 * setup-phase7d.js — CandidatIA
 * Phase 7d : Relances + Paiement
 *
 * Crée dans frontend/ :
 *   - components/relance/RelanceCard.tsx
 *   - components/relance/ScheduleModal.tsx
 *   - components/billing/PlanCard.tsx
 *   - components/billing/PaymentMethods.tsx
 *   - app/[locale]/dashboard/relances/page.tsx
 *   - app/[locale]/dashboard/billing/page.tsx
 *
 * Usage : node setup-phase7d.js
 * Prérequis : avoir exécuté setup-phase7c.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const FRONTEND = path.join(ROOT, 'frontend');

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeLines(relPath, lines) {
  const fullPath = path.join(FRONTEND, relPath);
  ensureDir(path.dirname(fullPath));
  fs.writeFileSync(fullPath, lines.join('\n') + '\n', 'utf-8');
  console.log('  OK  ' + relPath);
}

function logHeader(title) {
  console.log('');
  console.log('='.repeat(70));
  console.log('  ' + title);
  console.log('='.repeat(70));
  console.log('');
}

function logStep(step) {
  console.log('');
  console.log('> ' + step);
}

logHeader('CandidatIA — Setup Phase 7d : Relances + Paiement');

if (!fs.existsSync(path.join(FRONTEND, 'app', '[locale]', 'dashboard', 'history', 'page.tsx'))) {
  console.error('');
  console.error('  ERREUR : La Phase 7c doit etre executee avant.');
  console.error('');
  process.exit(1);
}

console.log('  Frontend : ' + FRONTEND);

// ============================================================
// 1. RELANCE CARD
// ============================================================

logStep('1. components/relance/RelanceCard.tsx');

writeLines('components/relance/RelanceCard.tsx', [
  '"use client";',
  '',
  'import { useState } from "react";',
  'import { Card, CardContent } from "@/components/ui/Card";',
  'import { Button } from "@/components/ui/Button";',
  '',
  'export interface Relance {',
  '  id: string;',
  '  company_name: string;',
  '  job_title: string;',
  '  wait_days: number;',
  '  scheduled_date: string;',
  '  email_draft: string;',
  '  status: string;',
  '}',
  '',
  'const STATUS_LABELS: Record<string, { label: string; color: string }> = {',
  '  pending: { label: "En attente", color: "bg-blue-100 text-blue-700" },',
  '  reminded: { label: "Rappel envoye", color: "bg-amber-100 text-amber-700" },',
  '  sent: { label: "Envoyee", color: "bg-emerald-100 text-emerald-700" },',
  '  cancelled: { label: "Annulee", color: "bg-slate-100 text-slate-500" },',
  '};',
  '',
  'export function RelanceCard({',
  '  relance,',
  '  onCancel,',
  '  onMarkSent,',
  '}: {',
  '  relance: Relance;',
  '  onCancel: (id: string) => void;',
  '  onMarkSent: (id: string) => void;',
  '}) {',
  '  const [showDraft, setShowDraft] = useState(false);',
  '  const statusInfo = STATUS_LABELS[relance.status] || STATUS_LABELS.pending;',
  '',
  '  return (',
  '    <Card>',
  '      <CardContent className="pt-6">',
  '        <div className="flex items-start justify-between gap-4">',
  '          <div className="flex-1 min-w-0">',
  '            <div className="flex items-center gap-3 mb-2">',
  '              <h3 className="font-bold text-dark truncate">{relance.job_title}</h3>',
  '              <span className={`px-2 py-0.5 text-xs font-medium rounded-full ${statusInfo.color}`}>',
  '                {statusInfo.label}',
  '              </span>',
  '            </div>',
  '            <p className="text-sm text-slate-600 mb-1">',
  '              {relance.company_name}',
  '            </p>',
  '            <p className="text-xs text-slate-500">',
  '              Relance prevue le {new Date(relance.scheduled_date).toLocaleDateString("fr-FR")} ',
  '              ({relance.wait_days} jours)',
  '            </p>',
  '          </div>',
  '        </div>',
  '',
  '        <div className="flex flex-wrap gap-2 mt-4">',
  '          <Button',
  '            variant="outline"',
  '            size="sm"',
  '            onClick={() => setShowDraft((v) => !v)}',
  '          >',
  '            {showDraft ? "Masquer" : "Voir"} le brouillon',
  '          </Button>',
  '',
  '          {relance.status === "pending" && (',
  '            <Button',
  '              variant="ghost"',
  '              size="sm"',
  '              onClick={() => onCancel(relance.id)}',
  '            >',
  '              Annuler',
  '            </Button>',
  '          )}',
  '',
  '          {(relance.status === "pending" || relance.status === "reminded") && (',
  '            <Button',
  '              size="sm"',
  '              onClick={() => onMarkSent(relance.id)}',
  '            >',
  '              Marquer comme envoyee',
  '            </Button>',
  '          )}',
  '        </div>',
  '',
  '        {showDraft && (',
  '          <div className="mt-4 p-4 bg-slate-50 rounded-lg border border-slate-200">',
  '            <p className="text-xs font-bold text-slate-700 mb-2">',
  '              Brouillon genere par IA :',
  '            </p>',
  '            <pre className="text-xs text-slate-600 whitespace-pre-wrap font-mono leading-relaxed">',
  '              {relance.email_draft}',
  '            </pre>',
  '          </div>',
  '        )}',
  '      </CardContent>',
  '    </Card>',
  '  );',
  '}',
]);

// ============================================================
// 2. SCHEDULE MODAL
// ============================================================

logStep('2. components/relance/ScheduleModal.tsx');

writeLines('components/relance/ScheduleModal.tsx', [
  '"use client";',
  '',
  'import { useState, FormEvent } from "react";',
  'import { api } from "@/lib/api";',
  'import { Button } from "@/components/ui/Button";',
  'import { Input } from "@/components/ui/Input";',
  'import { Alert } from "@/components/ui/Alert";',
  '',
  'const WAIT_OPTIONS = [3, 5, 7, 10, 14, 21, 30];',
  '',
  'export function ScheduleModal({',
  '  isOpen,',
  '  onClose,',
  '  onSuccess,',
  '}: {',
  '  isOpen: boolean;',
  '  onClose: () => void;',
  '  onSuccess: () => void;',
  '}) {',
  '  const [companyName, setCompanyName] = useState("");',
  '  const [jobTitle, setJobTitle] = useState("");',
  '  const [waitDays, setWaitDays] = useState(7);',
  '  const [language, setLanguage] = useState("fr");',
  '  const [loading, setLoading] = useState(false);',
  '  const [error, setError] = useState("");',
  '',
  '  if (!isOpen) return null;',
  '',
  '  async function handleSubmit(e: FormEvent) {',
  '    e.preventDefault();',
  '    setError("");',
  '    setLoading(true);',
  '',
  '    try {',
  '      await api.post("/api/relance/schedule", {',
  '        company_name: companyName,',
  '        job_title: jobTitle,',
  '        wait_days: waitDays,',
  '        language,',
  '      });',
  '',
  '      onSuccess();',
  '      onClose();',
  '    } catch (err: any) {',
  '      setError(err.response?.data?.detail || "Erreur de programmation.");',
  '    } finally {',
  '      setLoading(false);',
  '    }',
  '  }',
  '',
  '  return (',
  '    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50">',
  '      <div className="bg-white rounded-xl max-w-md w-full p-6 max-h-[90vh] overflow-y-auto">',
  '        <div className="flex items-center justify-between mb-4">',
  '          <h2 className="text-xl font-bold text-dark">Programmer une relance</h2>',
  '          <button',
  '            onClick={onClose}',
  '            className="text-slate-400 hover:text-slate-600 text-2xl leading-none"',
  '          >',
  '            x',
  '          </button>',
  '        </div>',
  '',
  '        <form onSubmit={handleSubmit} className="space-y-4">',
  '          {error && <Alert variant="error">{error}</Alert>}',
  '',
  '          <Input',
  '            label="Entreprise"',
  '            value={companyName}',
  '            onChange={(e) => setCompanyName(e.target.value)}',
  '            placeholder="TechCorp"',
  '            required',
  '          />',
  '',
  '          <Input',
  '            label="Poste"',
  '            value={jobTitle}',
  '            onChange={(e) => setJobTitle(e.target.value)}',
  '            placeholder="Developpeur Python Senior"',
  '            required',
  '          />',
  '',
  '          <div>',
  '            <label className="block text-sm font-medium text-slate-700 mb-1.5">',
  '              Delai avant relance',
  '            </label>',
  '            <select',
  '              value={waitDays}',
  '              onChange={(e) => setWaitDays(Number(e.target.value))}',
  '              className="w-full px-4 py-2.5 text-base border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"',
  '            >',
  '              {WAIT_OPTIONS.map((d) => (',
  '                <option key={d} value={d}>',
  '                  {d} jours',
  '                </option>',
  '              ))}',
  '            </select>',
  '          </div>',
  '',
  '          <div>',
  '            <label className="block text-sm font-medium text-slate-700 mb-1.5">',
  '              Langue du brouillon',
  '            </label>',
  '            <select',
  '              value={language}',
  '              onChange={(e) => setLanguage(e.target.value)}',
  '              className="w-full px-4 py-2.5 text-base border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500"',
  '            >',
  '              <option value="fr">Francais</option>',
  '              <option value="en">English</option>',
  '              <option value="es">Espanol</option>',
  '            </select>',
  '          </div>',
  '',
  '          <div className="flex gap-3 pt-2">',
  '            <Button type="button" variant="secondary" onClick={onClose} className="flex-1">',
  '              Annuler',
  '            </Button>',
  '            <Button type="submit" loading={loading} className="flex-1">',
  '              Programmer',
  '            </Button>',
  '          </div>',
  '',
  '          {loading && (',
  '            <Alert variant="info">',
  '              Generation du brouillon en cours... (30 secondes)',
  '            </Alert>',
  '          )}',
  '        </form>',
  '      </div>',
  '    </div>',
  '  );',
  '}',
]);

// ============================================================
// 3. RELANCES PAGE
// ============================================================

logStep('3. app/[locale]/dashboard/relances/page.tsx');

writeLines('app/[locale]/dashboard/relances/page.tsx', [
  '"use client";',
  '',
  'import { useEffect, useState } from "react";',
  'import { api } from "@/lib/api";',
  'import { Button } from "@/components/ui/Button";',
  'import { Alert } from "@/components/ui/Alert";',
  'import { RelanceCard, Relance } from "@/components/relance/RelanceCard";',
  'import { ScheduleModal } from "@/components/relance/ScheduleModal";',
  '',
  'export default function RelancesPage() {',
  '  const [relances, setRelances] = useState<Relance[]>([]);',
  '  const [loading, setLoading] = useState(true);',
  '  const [error, setError] = useState("");',
  '  const [showModal, setShowModal] = useState(false);',
  '',
  '  async function load() {',
  '    try {',
  '      const { data } = await api.get<Relance[]>("/api/relance");',
  '      setRelances(data);',
  '    } catch (err: any) {',
  '      setError(err.response?.data?.detail || "Erreur de chargement.");',
  '    } finally {',
  '      setLoading(false);',
  '    }',
  '  }',
  '',
  '  useEffect(() => {',
  '    load();',
  '  }, []);',
  '',
  '  async function handleCancel(id: string) {',
  '    if (!confirm("Annuler cette relance ?")) return;',
  '    try {',
  '      await api.post(`/api/relance/${id}/cancel`);',
  '      load();',
  '    } catch (err: any) {',
  '      alert(err.response?.data?.detail || "Erreur");',
  '    }',
  '  }',
  '',
  '  async function handleMarkSent(id: string) {',
  '    if (!confirm("Marquer comme envoyee ?")) return;',
  '    try {',
  '      await api.post(`/api/relance/${id}/mark-sent`);',
  '      load();',
  '    } catch (err: any) {',
  '      alert(err.response?.data?.detail || "Erreur");',
  '    }',
  '  }',
  '',
  '  return (',
  '    <div className="max-w-4xl mx-auto space-y-6">',
  '      <div className="flex items-start justify-between gap-4">',
  '        <div>',
  '          <h1 className="text-3xl font-bold text-dark mb-2">Relances</h1>',
  '          <p className="text-slate-600">',
  '            Programmez des rappels pour relancer vos candidatures.',
  '          </p>',
  '        </div>',
  '        <Button onClick={() => setShowModal(true)}>Nouvelle relance</Button>',
  '      </div>',
  '',
  '      {error && <Alert variant="error">{error}</Alert>}',
  '',
  '      {loading ? (',
  '        <p className="text-slate-500 text-sm">Chargement...</p>',
  '      ) : relances.length === 0 ? (',
  '        <div className="bg-white rounded-xl border border-slate-200 p-12 text-center">',
  '          <p className="text-slate-500 mb-2">Aucune relance programmee.</p>',
  '          <p className="text-sm text-slate-400">',
  '            Cliquez sur "Nouvelle relance" pour commencer.',
  '          </p>',
  '        </div>',
  '      ) : (',
  '        <div className="space-y-4">',
  '          {relances.map((r) => (',
  '            <RelanceCard',
  '              key={r.id}',
  '              relance={r}',
  '              onCancel={handleCancel}',
  '              onMarkSent={handleMarkSent}',
  '            />',
  '          ))}',
  '        </div>',
  '      )}',
  '',
  '      <ScheduleModal',
  '        isOpen={showModal}',
  '        onClose={() => setShowModal(false)}',
  '        onSuccess={load}',
  '      />',
  '    </div>',
  '  );',
  '}',
]);

// ============================================================
// 4. PLAN CARD
// ============================================================

logStep('4. components/billing/PlanCard.tsx');

writeLines('components/billing/PlanCard.tsx', [
  'import { cn } from "@/lib/utils";',
  '',
  'export interface Plan {',
  '  code: string;',
  '  name: string;',
  '  price_eur: number;',
  '  price_xof: number;',
  '  credits: number;',
  '  features: string[];',
  '}',
  '',
  'export function PlanCard({',
  '  plan,',
  '  isCurrentPlan,',
  '  onSelect,',
  '  highlighted = false,',
  '}: {',
  '  plan: Plan;',
  '  isCurrentPlan: boolean;',
  '  onSelect: (code: string) => void;',
  '  highlighted?: boolean;',
  '}) {',
  '  return (',
  '    <div',
  '      className={cn(',
  '        "relative bg-white rounded-xl border p-6 transition",',
  '        highlighted',
  '          ? "border-primary-500 shadow-lg shadow-primary-500/20"',
  '          : "border-slate-200 hover:border-primary-300",',
  '      )}',
  '    >',
  '      {highlighted && (',
  '        <span className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-1 text-xs font-bold text-white bg-primary-600 rounded-full">',
  '          POPULAIRE',
  '        </span>',
  '      )}',
  '',
  '      <h3 className="text-lg font-bold text-dark mb-2">{plan.name}</h3>',
  '      <div className="mb-4">',
  '        <span className="text-3xl font-bold text-dark">{plan.price_eur}</span>',
  '        <span className="text-slate-500 text-sm ml-1">EUR</span>',
  '      </div>',
  '      <p className="text-sm text-slate-500 mb-6">',
  '        {plan.credits} pack(s) de candidature',
  '      </p>',
  '',
  '      <ul className="space-y-2 mb-6">',
  '        {plan.features.map((feature, i) => (',
  '          <li key={i} className="flex items-start gap-2 text-sm text-slate-600">',
  '            <svg',
  '              width="16"',
  '              height="16"',
  '              viewBox="0 0 24 24"',
  '              fill="none"',
  '              stroke="currentColor"',
  '              strokeWidth="2"',
  '              className="text-emerald-500 shrink-0 mt-0.5"',
  '            >',
  '              <polyline points="20 6 9 17 4 12" />',
  '            </svg>',
  '            <span>{feature}</span>',
  '          </li>',
  '        ))}',
  '      </ul>',
  '',
  '      <button',
  '        onClick={() => onSelect(plan.code)}',
  '        disabled={isCurrentPlan}',
  '        className={cn(',
  '          "w-full py-2.5 rounded-lg font-semibold text-sm transition",',
  '          isCurrentPlan',
  '            ? "bg-slate-100 text-slate-400 cursor-not-allowed"',
  '            : highlighted',
  '            ? "bg-primary-600 text-white hover:bg-primary-700"',
  '            : "bg-slate-100 text-slate-700 hover:bg-slate-200",',
  '        )}',
  '      >',
  '        {isCurrentPlan ? "Plan actuel" : "Choisir ce plan"}',
  '      </button>',
  '    </div>',
  '  );',
  '}',
]);

// ============================================================
// 5. PAYMENT METHODS
// ============================================================

logStep('5. components/billing/PaymentMethods.tsx');

writeLines('components/billing/PaymentMethods.tsx', [
  'import { cn } from "@/lib/utils";',
  '',
  'export interface PaymentMethod {',
  '  provider: string;',
  '  label: string;',
  '  description: string;',
  '}',
  '',
  'export const PAYMENT_METHODS: PaymentMethod[] = [',
  '  {',
  '    provider: "fedapay",',
  '    label: "Mobile Money",',
  '    description: "MTN MoMo, Moov, Celtiis (Benin)",',
  '  },',
  '  {',
  '    provider: "flutterwave",',
  '    label: "Carte bancaire",',
  '    description: "Visa, Mastercard",',
  '  },',
  '  {',
  '    provider: "raenest",',
  '    label: "Crypto (USDT/USDC)",',
  '    description: "Paiement en stablecoins",',
  '  },',
  '];',
  '',
  'export function PaymentMethods({',
  '  availableProviders,',
  '  selected,',
  '  onSelect,',
  '}: {',
  '  availableProviders: string[];',
  '  selected: string;',
  '  onSelect: (provider: string) => void;',
  '}) {',
  '  return (',
  '    <div className="space-y-3">',
  '      {PAYMENT_METHODS.map((method) => {',
  '        const isAvailable = availableProviders.includes(method.provider);',
  '        const isSelected = selected === method.provider;',
  '',
  '        return (',
  '          <button',
  '            key={method.provider}',
  '            type="button"',
  '            disabled={!isAvailable}',
  '            onClick={() => onSelect(method.provider)}',
  '            className={cn(',
  '              "w-full p-4 rounded-lg border-2 text-left transition flex items-center gap-3",',
  '              !isAvailable',
  '                ? "border-slate-100 bg-slate-50 opacity-50 cursor-not-allowed"',
  '                : isSelected',
  '                ? "border-primary-500 bg-primary-50"',
  '                : "border-slate-200 hover:border-primary-300 bg-white",',
  '            )}',
  '          >',
  '            <div',
  '              className={cn(',
  '                "w-5 h-5 rounded-full border-2 flex items-center justify-center shrink-0",',
  '                isSelected ? "border-primary-500" : "border-slate-300",',
  '              )}',
  '            >',
  '              {isSelected && <div className="w-2.5 h-2.5 rounded-full bg-primary-500" />}',
  '            </div>',
  '            <div className="flex-1">',
  '              <p className="font-medium text-slate-700">{method.label}</p>',
  '              <p className="text-xs text-slate-500">{method.description}</p>',
  '            </div>',
  '            {!isAvailable && (',
  '              <span className="text-xs text-slate-400">Indisponible</span>',
  '            )}',
  '          </button>',
  '        );',
  '      })}',
  '    </div>',
  '  );',
  '}',
]);

// ============================================================
// 6. BILLING PAGE
// ============================================================

logStep('6. app/[locale]/dashboard/billing/page.tsx');

writeLines('app/[locale]/dashboard/billing/page.tsx', [
  '"use client";',
  '',
  'import { useEffect, useState } from "react";',
  'import { api } from "@/lib/api";',
  'import { useAuthStore } from "@/lib/store";',
  'import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/Card";',
  'import { Alert } from "@/components/ui/Alert";',
  'import { PlanCard, Plan } from "@/components/billing/PlanCard";',
  'import { PaymentMethods } from "@/components/billing/PaymentMethods";',
  '',
  'interface Payment {',
  '  id: string;',
  '  provider: string;',
  '  amount: number;',
  '  currency: string;',
  '  plan_purchased: string;',
  '  status: string;',
  '  created_at: string;',
  '}',
  '',
  'export default function BillingPage() {',
  '  const { user } = useAuthStore();',
  '',
  '  const [plans, setPlans] = useState<Plan[]>([]);',
  '  const [providers, setProviders] = useState<string[]>([]);',
  '  const [payments, setPayments] = useState<Payment[]>([]);',
  '  const [selectedProvider, setSelectedProvider] = useState("");',
  '  const [loading, setLoading] = useState(true);',
  '  const [checkingOut, setCheckingOut] = useState(false);',
  '  const [error, setError] = useState("");',
  '',
  '  useEffect(() => {',
  '    async function load() {',
  '      try {',
  '        const [plansRes, providersRes, paymentsRes, meRes] = await Promise.all([',
  '          api.get("/api/billing/plans"),',
  '          api.get("/api/billing/providers"),',
  '          api.get("/api/billing/payments"),',
  '          api.get("/api/auth/me"),',
  '        ]);',
  '',
  '        // Rafraichir les infos utilisateur (credits, plan)',
  '        useAuthStore.getState().setUser(meRes.data);',
  '',
  '        setPlans(plansRes.data.plans);',
  '        setProviders(providersRes.data.providers);',
  '        setPayments(paymentsRes.data);',
  '',
  '        if (providersRes.data.providers.length > 0) {',
  '          setSelectedProvider(providersRes.data.providers[0]);',
  '        }',
  '      } catch (err: any) {',
  '        setError(err.response?.data?.detail || "Erreur de chargement.");',
  '      } finally {',
  '        setLoading(false);',
  '      }',
  '    }',
  '    load();',
  '  }, []);',
  '',
  '  async function handleCheckout(planCode: string) {',
  '    if (!selectedProvider) {',
  '      setError("Selectionnez un moyen de paiement.");',
  '      return;',
  '    }',
  '',
  '    setError("");',
  '    setCheckingOut(true);',
  '',
  '    try {',
  '      const { data } = await api.post("/api/billing/checkout", {',
  '        plan_code: planCode,',
  '        provider: selectedProvider,',
  '      });',
  '',
  '      // Rediriger vers la page de paiement',
  '      window.location.href = data.checkout_url;',
  '    } catch (err: any) {',
  '      setError(err.response?.data?.detail || "Erreur de paiement.");',
  '      setCheckingOut(false);',
  '    }',
  '  }',
  '',
  '  return (',
  '    <div className="max-w-6xl mx-auto space-y-8">',
  '      <div>',
  '        <h1 className="text-3xl font-bold text-dark mb-2">Paiement</h1>',
  '        <p className="text-slate-600">',
  '          Choisissez un plan et reglez par Mobile Money, carte ou crypto.',
  '        </p>',
  '      </div>',
  '',
  '      {error && <Alert variant="error">{error}</Alert>}',
  '',
  '      <div>',
  '        <h2 className="text-xl font-bold text-dark mb-4">Nos plans</h2>',
  '        {loading ? (',
  '          <p className="text-slate-500 text-sm">Chargement des plans...</p>',
  '        ) : (',
  '          <div className="grid md:grid-cols-3 gap-6">',
  '            {plans.map((plan) => (',
  '              <PlanCard',
  '                key={plan.code}',
  '                plan={plan}',
  '                isCurrentPlan={user?.plan === plan.code}',
  '                onSelect={handleCheckout}',
  '                highlighted={plan.code === "pro"}',
  '              />',
  '            ))}',
  '          </div>',
  '        )}',
  '      </div>',
  '',
  '      <Card>',
  '        <CardHeader>',
  '          <CardTitle>Moyens de paiement</CardTitle>',
  '        </CardHeader>',
  '        <CardContent>',
  '          {providers.length === 0 ? (',
  '            <Alert variant="info">',
  '              Aucun moyen de paiement disponible actuellement. Configurez FedaPay dans le backend.',
  '            </Alert>',
  '          ) : (',
  '            <PaymentMethods',
  '              availableProviders={providers}',
  '              selected={selectedProvider}',
  '              onSelect={setSelectedProvider}',
  '            />',
  '          )}',
  '        </CardContent>',
  '      </Card>',
  '',
  '      <Card>',
  '        <CardHeader>',
  '          <CardTitle>Historique des paiements</CardTitle>',
  '        </CardHeader>',
  '        <CardContent>',
  '          {payments.length === 0 ? (',
  '            <p className="text-slate-500 text-sm text-center py-4">',
  '              Aucun paiement pour le moment.',
  '            </p>',
  '          ) : (',
  '            <div className="space-y-2">',
  '              {payments.map((p) => (',
  '                <div',
  '                  key={p.id}',
  '                  className="flex items-center justify-between p-3 bg-slate-50 rounded-lg text-sm"',
  '                >',
  '                  <div>',
  '                    <p className="font-medium text-slate-700">',
  '                      Plan {p.plan_purchased}',
  '                    </p>',
  '                    <p className="text-xs text-slate-500">',
  '                      {new Date(p.created_at).toLocaleString("fr-FR")}',
  '                    </p>',
  '                  </div>',
  '                  <div className="text-right">',
  '                    <p className="font-bold text-slate-700">',
  '                      {p.amount} {p.currency}',
  '                    </p>',
  '                    <p className="text-xs text-slate-500">{p.status}</p>',
  '                  </div>',
  '                </div>',
  '              ))}',
  '            </div>',
  '          )}',
  '        </CardContent>',
  '      </Card>',
  '    </div>',
  '  );',
  '}',
]);

// ============================================================
// RÉSUMÉ
// ============================================================

logHeader('Phase 7d terminee avec succes');

console.log('  Fichiers crees :');
console.log('    - frontend/components/relance/RelanceCard.tsx');
console.log('    - frontend/components/relance/ScheduleModal.tsx');
console.log('    - frontend/components/billing/PlanCard.tsx');
console.log('    - frontend/components/billing/PaymentMethods.tsx');
console.log('    - frontend/app/[locale]/dashboard/relances/page.tsx');
console.log('    - frontend/app/[locale]/dashboard/billing/page.tsx');
console.log('');
console.log('  VERIFICATION :');
console.log('');
console.log('  1. Next.js va recharger automatiquement.');
console.log('');
console.log('  2. Ouvrir :');
console.log('     http://localhost:3000/dashboard/relances');
console.log('     http://localhost:3000/dashboard/billing');
console.log('');
console.log('  Prochaine etape : setup-phase7e.js (Polish + Deploiement)');
console.log('');