#!/usr/bin/env node
/**
 * setup-phase1.js — CandidatIA
 * Phase 1 : Moteur IA multi-provider
 *
 * Crée :
 *   - Core backend (config, errors, logging, telemetry)
 *   - Moteur IA (schemas, base, 4 providers, json_repair, cache, orchestrator)
 *   - Routers (health)
 *   - main.py (point d'entrée FastAPI)
 *   - Tests unitaires complets
 *
 * Usage : node setup-phase1.js
 * Prérequis : avoir exécuté setup-phase0.js
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = process.cwd();

// ============================================================
// UTILITAIRES
// ============================================================

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function writeFile(relPath, content) {
  const fullPath = path.join(ROOT, relPath);
  ensureDir(path.dirname(fullPath));
  fs.writeFileSync(fullPath, content, 'utf-8');
  console.log('  OK  ' + relPath);
}

function writeLines(relPath, lines) {
  writeFile(relPath, lines.join('\n') + '\n');
}

function logHeader(title) {
  console.log('');
  console.log('='.repeat(70));
  console.log('  ' + title);
  console.log('='.repeat(70));
  console.log('');
}

function logStep(step) {
  console.log('');
  console.log('> ' + step);
}

// ============================================================
// VÉRIFICATIONS
// ============================================================

logHeader('CandidatIA — Setup Phase 1 : Moteur IA multi-provider');

if (!fs.existsSync(path.join(ROOT, 'backend', 'app'))) {
  console.error('');
  console.error('  ERREUR : Le dossier backend/app est introuvable.');
  console.error('  Execute d abord setup-phase0.js dans ce dossier.');
  console.error('');
  process.exit(1);
}

console.log('  Racine du projet : ' + ROOT);
console.log('');

// ============================================================
// 1. CORE — CONFIG
// ============================================================

logStep('1. Core — config.py');

writeLines('backend/app/core/config.py', [
  '"""',
  'Configuration centralisee de l application.',
  'Toutes les variables d environnement sont typees et validees ici.',
  '"""',
  '',
  'from functools import lru_cache',
  'from typing import List, Literal',
  '',
  'from pydantic import Field, field_validator',
  'from pydantic_settings import BaseSettings, SettingsConfigDict',
  '',
  '',
  'class Settings(BaseSettings):',
  '    """Configuration globale, chargee depuis .env ou variables d environnement."""',
  '',
  '    model_config = SettingsConfigDict(',
  '        env_file=".env",',
  '        env_file_encoding="utf-8",',
  '        case_sensitive=False,',
  '        extra="ignore",',
  '    )',
  '',
  '    # ---------- General ----------',
  '    app_name: str = "CandidatIA"',
  '    app_env: Literal["development", "staging", "production"] = "development"',
  '    app_debug: bool = True',
  '    app_host: str = "0.0.0.0"',
  '    app_port: int = 8000',
  '    app_base_url: str = "http://localhost:8000"',
  '    frontend_url: str = "http://localhost:3000"',
  '',
  '    # ---------- Securite ----------',
  '    secret_key: str = Field(..., min_length=16)',
  '    jwt_algorithm: str = "HS256"',
  '    jwt_expiration_minutes: int = 60',
  '',
  '    # ---------- IA Providers ----------',
  '    groq_api_key: str = ""',
  '    gemini_api_key: str = ""',
  '    mistral_api_key: str = ""',
  '    cohere_api_key: str = ""',
  '',
  '    ai_provider_order: str = "groq,gemini,mistral,cohere"',
  '    ai_timeout_seconds: int = 60',
  '    ai_max_retries: int = 2',
  '    ai_circuit_breaker_threshold: int = 3',
  '    ai_circuit_breaker_cooldown: int = 300',
  '',
  '    # ---------- Supabase ----------',
  '    supabase_url: str = ""',
  '    supabase_anon_key: str = ""',
  '    supabase_service_key: str = ""',
  '    database_url: str = ""',
  '',
  '    # ---------- Redis ----------',
  '    redis_url: str = "redis://localhost:6379"',
  '    upstash_redis_url: str = ""',
  '    upstash_redis_token: str = ""',
  '',
  '    # ---------- Brevo ----------',
  '    brevo_api_key: str = ""',
  '    brevo_sender_email: str = "noreply@candidatia.com"',
  '    brevo_sender_name: str = "CandidatIA"',
  '',
  '    # ---------- FedaPay ----------',
  '    fedapay_secret_key: str = ""',
  '    fedapay_public_key: str = ""',
  '    fedapay_env: Literal["sandbox", "live"] = "sandbox"',
  '    fedapay_webhook_secret: str = ""',
  '',
  '    # ---------- Flutterwave ----------',
  '    flutterwave_secret_key: str = ""',
  '    flutterwave_public_key: str = ""',
  '    flutterwave_webhook_secret: str = ""',
  '',
  '    # ---------- Raenest ----------',
  '    raenest_api_key: str = ""',
  '    raenest_webhook_secret: str = ""',
  '',
  '    # ---------- Stockage ----------',
  '    storage_provider: Literal["local", "supabase"] = "local"',
  '    supabase_storage_bucket: str = "candidatia-packs"',
  '    local_storage_path: str = "./fichiers_generes"',
  '    max_file_size_mb: int = 10',
  '',
  '    # ---------- Observabilite ----------',
  '    sentry_dsn: str = ""',
  '    log_level: str = "INFO"',
  '',
  '    # ---------- Quotas ----------',
  '    quota_free_monthly: int = 1',
  '    quota_essentiel_total: int = 5',
  '    quota_pro_monthly: int = 30',
  '',
  '    # ---------- Proprietes calculees ----------',
  '    @property',
  '    def ai_providers_list(self) -> List[str]:',
  '        return [p.strip().lower() for p in self.ai_provider_order.split(",") if p.strip()]',
  '',
  '    @property',
  '    def is_production(self) -> bool:',
  '        return self.app_env == "production"',
  '',
  '    @property',
  '    def is_development(self) -> bool:',
  '        return self.app_env == "development"',
  '',
  '    # ---------- Validators ----------',
  '    @field_validator("secret_key")',
  '    @classmethod',
  '    def validate_secret_key(cls, v: str) -> str:',
  '        if len(v) < 16:',
  '            raise ValueError("SECRET_KEY doit faire au moins 16 caracteres")',
  '        return v',
  '',
  '',
  '@lru_cache',
  'def get_settings() -> Settings:',
  '    """Singleton de configuration."""',
  '    return Settings()  # type: ignore[call-arg]',
]);

// ============================================================
// 2. CORE — ERRORS
// ============================================================

logStep('2. Core — errors.py');

writeLines('backend/app/core/errors.py', [
  '"""Exceptions typees de l application."""',
  '',
  'from typing import Any, Dict, Optional',
  '',
  '',
  'class AppError(Exception):',
  '    """Exception de base de l application."""',
  '',
  '    status_code: int = 500',
  '    error_code: str = "INTERNAL_ERROR"',
  '    message: str = "Une erreur interne est survenue."',
  '',
  '    def __init__(',
  '        self,',
  '        message: Optional[str] = None,',
  '        details: Optional[Dict[str, Any]] = None,',
  '    ) -> None:',
  '        self.message = message or self.message',
  '        self.details = details or {}',
  '        super().__init__(self.message)',
  '',
  '    def to_dict(self) -> Dict[str, Any]:',
  '        return {',
  '            "error_code": self.error_code,',
  '            "message": self.message,',
  '            "details": self.details,',
  '        }',
  '',
  '',
  '# ---------- 4xx ----------',
  'class ValidationError(AppError):',
  '    status_code = 400',
  '    error_code = "VALIDATION_ERROR"',
  '    message = "Les donnees fournies sont invalides."',
  '',
  '',
  'class UnauthorizedError(AppError):',
  '    status_code = 401',
  '    error_code = "UNAUTHORIZED"',
  '    message = "Authentification requise."',
  '',
  '',
  'class ForbiddenError(AppError):',
  '    status_code = 403',
  '    error_code = "FORBIDDEN"',
  '    message = "Acces refuse."',
  '',
  '',
  'class NotFoundError(AppError):',
  '    status_code = 404',
  '    error_code = "NOT_FOUND"',
  '    message = "Ressource introuvable."',
  '',
  '',
  'class QuotaExceededError(AppError):',
  '    status_code = 402',
  '    error_code = "QUOTA_EXCEEDED"',
  '    message = "Quota de generations depasse. Veuillez passer a un plan superieur."',
  '',
  '',
  'class RateLimitError(AppError):',
  '    status_code = 429',
  '    error_code = "RATE_LIMIT"',
  '    message = "Trop de requetes. Veuillez reessayer dans quelques instants."',
  '',
  '',
  '# ---------- 5xx ----------',
  'class IngestionError(AppError):',
  '    status_code = 422',
  '    error_code = "INGESTION_ERROR"',
  '    message = "Impossible d extraire le contenu du fichier fourni."',
  '',
  '',
  'class AIProviderError(AppError):',
  '    status_code = 502',
  '    error_code = "AI_PROVIDER_ERROR"',
  '    message = "Le service IA est temporairement indisponible."',
  '',
  '',
  'class GenerationError(AppError):',
  '    status_code = 500',
  '    error_code = "GENERATION_ERROR"',
  '    message = "Erreur lors de la generation du document."',
  '',
  '',
  'class PaymentError(AppError):',
  '    status_code = 502',
  '    error_code = "PAYMENT_ERROR"',
  '    message = "Erreur lors du traitement du paiement."',
  '',
  '',
  'class StorageError(AppError):',
  '    status_code = 500',
  '    error_code = "STORAGE_ERROR"',
  '    message = "Erreur de stockage du document."',
]);

// ============================================================
// 3. CORE — LOGGING
// ============================================================

logStep('3. Core — logging.py');

writeLines('backend/app/core/logging.py', [
  '"""Configuration des logs structures via structlog."""',
  '',
  'import logging',
  'import sys',
  '',
  'import structlog',
  '',
  '',
  'def setup_logging(log_level: str = "INFO", is_production: bool = False) -> None:',
  '    logging.basicConfig(',
  '        format="%(message)s",',
  '        stream=sys.stdout,',
  '        level=getattr(logging, log_level.upper(), logging.INFO),',
  '    )',
  '',
  '    shared_processors = [',
  '        structlog.contextvars.merge_contextvars,',
  '        structlog.processors.add_log_level,',
  '        structlog.processors.TimeStamper(fmt="iso"),',
  '        structlog.processors.StackInfoRenderer(),',
  '    ]',
  '',
  '    if is_production:',
  '        processors = shared_processors + [',
  '            structlog.processors.format_exc_info,',
  '            structlog.processors.JSONRenderer(),',
  '        ]',
  '    else:',
  '        processors = shared_processors + [',
  '            structlog.dev.ConsoleRenderer(colors=True),',
  '        ]',
  '',
  '    structlog.configure(',
  '        processors=processors,',
  '        wrapper_class=structlog.make_filtering_bound_logger(',
  '            getattr(logging, log_level.upper(), logging.INFO)',
  '        ),',
  '        context_class=dict,',
  '        logger_factory=structlog.PrintLoggerFactory(),',
  '        cache_logger_on_first_use=True,',
  '    )',
  '',
  '',
  'def get_logger(name: str = "candidatia"):',
  '    """Retourne un logger structure."""',
  '    return structlog.get_logger(name)',
]);

// ============================================================
// 4. CORE — TELEMETRY
// ============================================================

logStep('4. Core — telemetry.py');

writeLines('backend/app/core/telemetry.py', [
  '"""Initialisation de Sentry pour la remontee d erreurs."""',
  '',
  'import sentry_sdk',
  'from sentry_sdk.integrations.fastapi import FastApiIntegration',
  'from sentry_sdk.integrations.starlette import StarletteIntegration',
  '',
  'from app.core.config import get_settings',
  '',
  '',
  'def setup_sentry() -> None:',
  '    """Initialise Sentry si un DSN est fourni."""',
  '    settings = get_settings()',
  '',
  '    if not settings.sentry_dsn:',
  '        return',
  '',
  '    sentry_sdk.init(',
  '        dsn=settings.sentry_dsn,',
  '        environment=settings.app_env,',
  '        traces_sample_rate=0.1 if settings.is_production else 1.0,',
  '        profiles_sample_rate=0.1 if settings.is_production else 0.0,',
  '        integrations=[',
  '            StarletteIntegration(transaction_style="endpoint"),',
  '            FastApiIntegration(transaction_style="endpoint"),',
  '        ],',
  '        send_default_pii=False,',
  '    )',
]);

// ============================================================
// 5. AI — SCHEMAS
// ============================================================

logStep('5. AI — schemas.py');

writeLines('backend/app/services/ai/schemas.py', [
  '"""Schemas Pydantic partages par le moteur IA."""',
  '',
  'from typing import Any, Dict, Optional',
  '',
  'from pydantic import BaseModel',
  '',
  '',
  'class AIMessage(BaseModel):',
  '    """Message individuel dans une conversation."""',
  '    role: str',
  '    content: str',
  '',
  '',
  'class AIRequest(BaseModel):',
  '    """Requete normalisee vers un provider IA."""',
  '    system_prompt: str',
  '    user_prompt: str',
  '    temperature: float = 0.2',
  '    max_tokens: Optional[int] = None',
  '    response_format_json: bool = True',
  '',
  '',
  'class AIResponse(BaseModel):',
  '    """Reponse normalisee d un provider IA."""',
  '    content: str',
  '    provider: str',
  '    model: str',
  '    tokens_input: Optional[int] = None',
  '    tokens_output: Optional[int] = None',
  '    latency_ms: int = 0',
  '    raw: Optional[Dict[str, Any]] = None',
  '',
  '',
  'class AIProviderInfo(BaseModel):',
  '    """Metadonnees d un provider."""',
  '    name: str',
  '    model: str',
  '    available: bool',
  '    priority: int = 0',
]);

// ============================================================
// 6. AI — BASE (interface abstraite)
// ============================================================

logStep('6. AI — base.py');

writeLines('backend/app/services/ai/base.py', [
  '"""',
  'Interface abstraite de tout provider IA.',
  '',
  'Chaque provider (Groq, Gemini, Mistral, Cohere) doit implementer cette interface.',
  'Cela garantit que l orchestrateur peut basculer d un provider a l autre sans',
  'connaitre les details d implementation.',
  '"""',
  '',
  'import time',
  'from abc import ABC, abstractmethod',
  '',
  'from app.core.errors import AIProviderError',
  'from app.services.ai.schemas import AIRequest, AIResponse',
  '',
  '',
  'class AIProvider(ABC):',
  '    """Classe abstraite pour un provider IA."""',
  '',
  '    name: str = "base"',
  '    model: str = ""',
  '',
  '    @abstractmethod',
  '    def is_available(self) -> bool:',
  '        """Retourne True si le provider est configure (cle API presente)."""',
  '        ...',
  '',
  '    @abstractmethod',
  '    def _call_api(self, request: AIRequest) -> AIResponse:',
  '        """Appel bas niveau a l API du provider."""',
  '        ...',
  '',
  '    def generate(self, request: AIRequest) -> AIResponse:',
  '        """Point d entree public. Gere le timing et les erreurs."""',
  '        if not self.is_available():',
  '            raise AIProviderError(',
  '                message=f"Provider {self.name} non configure (cle API manquante).",',
  '                details={"provider": self.name},',
  '            )',
  '',
  '        start = time.perf_counter()',
  '        try:',
  '            response = self._call_api(request)',
  '            response.latency_ms = int((time.perf_counter() - start) * 1000)',
  '            return response',
  '        except AIProviderError:',
  '            raise',
  '        except Exception as e:',
  '            raise AIProviderError(',
  '                message=f"Erreur provider {self.name}: {str(e)}",',
  '                details={"provider": self.name, "error": str(e)},',
  '            ) from e',
]);

// ============================================================
// 7. AI — GROQ
// ============================================================

logStep('7. AI — groq.py');

writeLines('backend/app/services/ai/groq.py', [
  '"""Provider IA : Groq (Llama 3.3 70B — gratuit, ultra-rapide)."""',
  '',
  'from groq import Groq',
  '',
  'from app.core.config import get_settings',
  'from app.core.logging import get_logger',
  'from app.services.ai.base import AIProvider',
  'from app.services.ai.schemas import AIRequest, AIResponse',
  '',
  'logger = get_logger("ai.groq")',
  '',
  '',
  'class GroqProvider(AIProvider):',
  '    name = "groq"',
  '    model = "llama-3.3-70b-versatile"',
  '',
  '    def __init__(self) -> None:',
  '        self.settings = get_settings()',
  '        self._client = None',
  '',
  '    def is_available(self) -> bool:',
  '        return bool(self.settings.groq_api_key)',
  '',
  '    def _get_client(self) -> Groq:',
  '        if self._client is None:',
  '            self._client = Groq(api_key=self.settings.groq_api_key)',
  '        return self._client',
  '',
  '    def _call_api(self, request: AIRequest) -> AIResponse:',
  '        client = self._get_client()',
  '',
  '        kwargs = {',
  '            "model": self.model,',
  '            "messages": [',
  '                {"role": "system", "content": request.system_prompt},',
  '                {"role": "user", "content": request.user_prompt},',
  '            ],',
  '            "temperature": request.temperature,',
  '        }',
  '',
  '        if request.response_format_json:',
  '            kwargs["response_format"] = {"type": "json_object"}',
  '',
  '        if request.max_tokens:',
  '            kwargs["max_tokens"] = request.max_tokens',
  '',
  '        completion = client.chat.completions.create(**kwargs)',
  '        content = completion.choices[0].message.content or ""',
  '',
  '        usage = getattr(completion, "usage", None)',
  '        return AIResponse(',
  '            content=content,',
  '            provider=self.name,',
  '            model=self.model,',
  '            tokens_input=getattr(usage, "prompt_tokens", None) if usage else None,',
  '            tokens_output=getattr(usage, "completion_tokens", None) if usage else None,',
  '        )',
]);

// ============================================================
// 8. AI — GEMINI
// ============================================================

logStep('8. AI — gemini.py');

writeLines('backend/app/services/ai/gemini.py', [
  '"""Provider IA : Google Gemini (Flash — gratuit)."""',
  '',
  'import google.generativeai as genai',
  '',
  'from app.core.config import get_settings',
  'from app.core.logging import get_logger',
  'from app.services.ai.base import AIProvider',
  'from app.services.ai.schemas import AIRequest, AIResponse',
  '',
  'logger = get_logger("ai.gemini")',
  '',
  '',
  'class GeminiProvider(AIProvider):',
  '    name = "gemini"',
  '    model = "gemini-1.5-flash"',
  '',
  '    def __init__(self) -> None:',
  '        self.settings = get_settings()',
  '        self._configured = False',
  '',
  '    def is_available(self) -> bool:',
  '        return bool(self.settings.gemini_api_key)',
  '',
  '    def _configure(self) -> None:',
  '        if not self._configured:',
  '            genai.configure(api_key=self.settings.gemini_api_key)',
  '            self._configured = True',
  '',
  '    def _call_api(self, request: AIRequest) -> AIResponse:',
  '        self._configure()',
  '',
  '        generation_config = {',
  '            "temperature": request.temperature,',
  '        }',
  '        if request.response_format_json:',
  '            generation_config["response_mime_type"] = "application/json"',
  '        if request.max_tokens:',
  '            generation_config["max_output_tokens"] = request.max_tokens',
  '',
  '        model = genai.GenerativeModel(',
  '            model_name=self.model,',
  '            system_instruction=request.system_prompt,',
  '            generation_config=generation_config,',
  '        )',
  '',
  '        response = model.generate_content(request.user_prompt)',
  '        content = response.text or ""',
  '',
  '        usage = getattr(response, "usage_metadata", None)',
  '        return AIResponse(',
  '            content=content,',
  '            provider=self.name,',
  '            model=self.model,',
  '            tokens_input=getattr(usage, "prompt_token_count", None) if usage else None,',
  '            tokens_output=getattr(usage, "candidates_token_count", None) if usage else None,',
  '        )',
]);

// ============================================================
// 9. AI — MISTRAL
// ============================================================

logStep('9. AI — mistral.py');

writeLines('backend/app/services/ai/mistral.py', [
  '"""Provider IA : Mistral AI (Small — gratuit)."""',
  '',
  'from mistralai import Mistral',
  '',
  'from app.core.config import get_settings',
  'from app.core.logging import get_logger',
  'from app.services.ai.base import AIProvider',
  'from app.services.ai.schemas import AIRequest, AIResponse',
  '',
  'logger = get_logger("ai.mistral")',
  '',
  '',
  'class MistralProvider(AIProvider):',
  '    name = "mistral"',
  '    model = "mistral-small-latest"',
  '',
  '    def __init__(self) -> None:',
  '        self.settings = get_settings()',
  '        self._client = None',
  '',
  '    def is_available(self) -> bool:',
  '        return bool(self.settings.mistral_api_key)',
  '',
  '    def _get_client(self) -> Mistral:',
  '        if self._client is None:',
  '            self._client = Mistral(api_key=self.settings.mistral_api_key)',
  '        return self._client',
  '',
  '    def _call_api(self, request: AIRequest) -> AIResponse:',
  '        client = self._get_client()',
  '',
  '        kwargs = {',
  '            "model": self.model,',
  '            "messages": [',
  '                {"role": "system", "content": request.system_prompt},',
  '                {"role": "user", "content": request.user_prompt},',
  '            ],',
  '            "temperature": request.temperature,',
  '        }',
  '',
  '        if request.response_format_json:',
  '            kwargs["response_format"] = {"type": "json_object"}',
  '',
  '        if request.max_tokens:',
  '            kwargs["max_tokens"] = request.max_tokens',
  '',
  '        completion = client.chat.complete(**kwargs)',
  '        content = completion.choices[0].message.content or ""',
  '',
  '        usage = getattr(completion, "usage", None)',
  '        return AIResponse(',
  '            content=content,',
  '            provider=self.name,',
  '            model=self.model,',
  '            tokens_input=getattr(usage, "prompt_tokens", None) if usage else None,',
  '            tokens_output=getattr(usage, "completion_tokens", None) if usage else None,',
  '        )',
]);

// ============================================================
// 10. AI — COHERE
// ============================================================

logStep('10. AI — cohere.py');

writeLines('backend/app/services/ai/cohere.py', [
  '"""Provider IA : Cohere (Command R — quota gratuit mensuel)."""',
  '',
  'import cohere',
  '',
  'from app.core.config import get_settings',
  'from app.core.logging import get_logger',
  'from app.services.ai.base import AIProvider',
  'from app.services.ai.schemas import AIRequest, AIResponse',
  '',
  'logger = get_logger("ai.cohere")',
  '',
  '',
  'class CohereProvider(AIProvider):',
  '    name = "cohere"',
  '    model = "command-r-08-2024"',
  '',
  '    def __init__(self) -> None:',
  '        self.settings = get_settings()',
  '        self._client = None',
  '',
  '    def is_available(self) -> bool:',
  '        return bool(self.settings.cohere_api_key)',
  '',
  '    def _get_client(self):',
  '        if self._client is None:',
  '            self._client = cohere.Client(api_key=self.settings.cohere_api_key)',
  '        return self._client',
  '',
  '    def _call_api(self, request: AIRequest) -> AIResponse:',
  '        client = self._get_client()',
  '',
  '        response = client.chat(',
  '            model=self.model,',
  '            message=request.user_prompt,',
  '            preamble=request.system_prompt,',
  '            temperature=request.temperature,',
  '        )',
  '',
  '        content = response.text or ""',
  '        meta = getattr(response, "meta", None)',
  '        tokens = getattr(meta, "tokens", None) if meta else None',
  '',
  '        return AIResponse(',
  '            content=content,',
  '            provider=self.name,',
  '            model=self.model,',
  '            tokens_input=getattr(tokens, "input_tokens", None) if tokens else None,',
  '            tokens_output=getattr(tokens, "output_tokens", None) if tokens else None,',
  '        )',
]);

// ============================================================
// 11. AI — JSON REPAIR
// ============================================================

logStep('11. AI — json_repair.py');

writeLines('backend/app/services/ai/json_repair.py', [
  '"""',
  'Utilitaire de reparation JSON.',
  '',
  'Les modeles gratuits coupent parfois leur reponse avant la fin. Ce module',
  'tente de reparer un JSON tronque en fermant les accolades/crochets ouverts.',
  '"""',
  '',
  'import json',
  'import re',
  'from typing import Any, Dict',
  '',
  'from app.core.errors import AIProviderError',
  'from app.core.logging import get_logger',
  '',
  'logger = get_logger("ai.json_repair")',
  '',
  '',
  'def _strip_markdown_fences(text: str) -> str:',
  '    """Retire les fences Markdown."""',
  '    text = text.strip()',
  '',
  '    if text.startswith("```json"):',
  '        text = text.split("```json", 1)[1]',
  '    elif text.startswith("```"):',
  '        text = text.split("```", 1)[1]',
  '',
  '    if "```" in text:',
  '        text = text.split("```", 1)[0]',
  '',
  '    return text.strip()',
  '',
  '',
  'def _close_unbalanced(text: str) -> str:',
  '    """Ferme les accolades et crochets ouverts."""',
  '    open_braces = text.count("{") - text.count("}")',
  '    open_brackets = text.count("[") - text.count("]")',
  '',
  '    if open_brackets > 0:',
  '        text += "]" * open_brackets',
  '    if open_braces > 0:',
  '        text += "}" * open_braces',
  '',
  '    return text',
  '',
  '',
  'def _remove_trailing_commas(text: str) -> str:',
  '    """Retire les virgules finales avant } ou ]."""',
  '    text = re.sub(r",\\s*}", "}", text)',
  '    text = re.sub(r",\\s*]", "]", text)',
  '    return text',
  '',
  '',
  'def parse_json_safely(raw: str) -> Dict[str, Any]:',
  '    """Tente de parser un JSON brut, avec reparation automatique."""',
  '    if not raw or not raw.strip():',
  '        raise AIProviderError(message="Reponse IA vide.")',
  '',
  '    cleaned = _strip_markdown_fences(raw)',
  '',
  '    # Tentative directe',
  '    try:',
  '        return json.loads(cleaned)',
  '    except json.JSONDecodeError:',
  '        pass',
  '',
  '    # Tentative apres fermeture des structures ouvertes',
  '    repaired = _close_unbalanced(cleaned)',
  '    repaired = _remove_trailing_commas(repaired)',
  '',
  '    try:',
  '        return json.loads(repaired)',
  '    except json.JSONDecodeError as e:',
  '        logger.warning(',
  '            "json_repair_failed",',
  '            error=str(e),',
  '            preview=cleaned[:200],',
  '        )',
  '        raise AIProviderError(',
  '            message="Impossible de parser la reponse IA en JSON.",',
  '            details={"error": str(e), "preview": cleaned[:200]},',
  '        ) from e',
]);

// ============================================================
// 12. AI — CACHE
// ============================================================

logStep('12. AI — cache.py');

writeLines('backend/app/services/ai/cache.py', [
  '"""',
  'Cache Redis pour les reponses IA.',
  '',
  'Evite de re-solliciter les providers pour des prompts identiques.',
  'Gain estime : 40-60% des appels en production.',
  '"""',
  '',
  'import hashlib',
  'import json',
  'from typing import Any, Dict, Optional',
  '',
  'from app.core.config import get_settings',
  'from app.core.logging import get_logger',
  '',
  'logger = get_logger("ai.cache")',
  '',
  'try:',
  '    import redis as redis_sync',
  '    _REDIS_AVAILABLE = True',
  'except ImportError:',
  '    _REDIS_AVAILABLE = False',
  '',
  '',
  'class AICache:',
  '    """Cache cle-valeur pour les reponses IA."""',
  '',
  '    DEFAULT_TTL = 60 * 60 * 24  # 24h',
  '',
  '    def __init__(self) -> None:',
  '        self.settings = get_settings()',
  '        self._client = None',
  '',
  '    def _get_client(self):',
  '        if not _REDIS_AVAILABLE:',
  '            return None',
  '',
  '        if self._client is None:',
  '            try:',
  '                self._client = redis_sync.from_url(',
  '                    self.settings.redis_url,',
  '                    decode_responses=True,',
  '                    socket_timeout=2,',
  '                )',
  '                self._client.ping()',
  '            except Exception as e:',
  '                logger.warning("redis_unavailable", error=str(e))',
  '                self._client = None',
  '',
  '        return self._client',
  '',
  '    @staticmethod',
  '    def make_key(system_prompt: str, user_prompt: str) -> str:',
  '        """Genere une cle de cache deterministe."""',
  '        payload = f"{system_prompt}\\n---\\n{user_prompt}"',
  '        return "ai:" + hashlib.sha256(payload.encode("utf-8")).hexdigest()',
  '',
  '    def get(self, key: str) -> Optional[Dict[str, Any]]:',
  '        """Recupere une reponse en cache ou None."""',
  '        client = self._get_client()',
  '        if not client:',
  '            return None',
  '',
  '        try:',
  '            data = client.get(key)',
  '            if data:',
  '                logger.info("cache_hit", key=key[:16])',
  '                return json.loads(data)',
  '        except Exception as e:',
  '            logger.warning("cache_get_error", error=str(e))',
  '',
  '        return None',
  '',
  '    def set(',
  '        self,',
  '        key: str,',
  '        value: Dict[str, Any],',
  '        ttl: int = DEFAULT_TTL,',
  '    ) -> None:',
  '        """Stocke une reponse en cache."""',
  '        client = self._get_client()',
  '        if not client:',
  '            return',
  '',
  '        try:',
  '            client.setex(key, ttl, json.dumps(value))',
  '        except Exception as e:',
  '            logger.warning("cache_set_error", error=str(e))',
  '',
  '',
  '# Singleton',
  '_cache_instance: Optional[AICache] = None',
  '',
  '',
  'def get_cache() -> AICache:',
  '    global _cache_instance',
  '    if _cache_instance is None:',
  '        _cache_instance = AICache()',
  '    return _cache_instance',
]);

// ============================================================
// 13. AI — ORCHESTRATOR
// ============================================================

logStep('13. AI — orchestrator.py');

writeLines('backend/app/services/ai/orchestrator.py', [
  '"""',
  'Orchestrateur IA multi-provider.',
  '',
  'Fonctionnement :',
  '1. Recoit une requete normalisee.',
  '2. Verifie le cache.',
  '3. Essaie les providers dans l ordre de priorite (configurable).',
  '4. Si un provider echoue, passe au suivant automatiquement.',
  '5. Applique un circuit breaker : apres N echecs, met le provider en pause.',
  '6. Ecrit la reponse en cache avant de la retourner.',
  '"""',
  '',
  'import time',
  'from typing import Any, Dict, List, Optional',
  '',
  'from app.core.config import get_settings',
  'from app.core.errors import AIProviderError',
  'from app.core.logging import get_logger',
  'from app.services.ai.base import AIProvider',
  'from app.services.ai.cache import get_cache',
  'from app.services.ai.cohere import CohereProvider',
  'from app.services.ai.gemini import GeminiProvider',
  'from app.services.ai.groq import GroqProvider',
  'from app.services.ai.json_repair import parse_json_safely',
  'from app.services.ai.mistral import MistralProvider',
  'from app.services.ai.schemas import AIRequest, AIResponse',
  '',
  'logger = get_logger("ai.orchestrator")',
  '',
  '',
  'class CircuitBreaker:',
  '    """Circuit breaker par provider."""',
  '',
  '    def __init__(self, threshold: int, cooldown_seconds: int) -> None:',
  '        self.threshold = threshold',
  '        self.cooldown_seconds = cooldown_seconds',
  '        self._failures: Dict[str, int] = {}',
  '        self._open_until: Dict[str, float] = {}',
  '',
  '    def is_open(self, provider_name: str) -> bool:',
  '        """Retourne True si le provider est en pause."""',
  '        until = self._open_until.get(provider_name, 0)',
  '        if until and time.time() < until:',
  '            return True',
  '        if until and time.time() >= until:',
  '            self._open_until.pop(provider_name, None)',
  '            self._failures.pop(provider_name, None)',
  '        return False',
  '',
  '    def record_success(self, provider_name: str) -> None:',
  '        self._failures[provider_name] = 0',
  '',
  '    def record_failure(self, provider_name: str) -> None:',
  '        self._failures[provider_name] = self._failures.get(provider_name, 0) + 1',
  '        if self._failures[provider_name] >= self.threshold:',
  '            self._open_until[provider_name] = time.time() + self.cooldown_seconds',
  '            logger.warning(',
  '                "circuit_breaker_open",',
  '                provider=provider_name,',
  '                cooldown=self.cooldown_seconds,',
  '            )',
  '',
  '',
  'class AIOrchestrator:',
  '    """Orchestrateur principal."""',
  '',
  '    def __init__(self) -> None:',
  '        self.settings = get_settings()',
  '        self.cache = get_cache()',
  '        self.breaker = CircuitBreaker(',
  '            threshold=self.settings.ai_circuit_breaker_threshold,',
  '            cooldown_seconds=self.settings.ai_circuit_breaker_cooldown,',
  '        )',
  '        self._providers: Dict[str, AIProvider] = {',
  '            "groq": GroqProvider(),',
  '            "gemini": GeminiProvider(),',
  '            "mistral": MistralProvider(),',
  '            "cohere": CohereProvider(),',
  '        }',
  '',
  '    def _ordered_providers(self) -> List[AIProvider]:',
  '        """Retourne les providers dans l ordre configure, disponibles et non en pause."""',
  '        ordered: List[AIProvider] = []',
  '        for name in self.settings.ai_providers_list:',
  '            provider = self._providers.get(name)',
  '            if not provider:',
  '                continue',
  '            if not provider.is_available():',
  '                logger.debug("provider_unavailable", provider=name)',
  '                continue',
  '            if self.breaker.is_open(name):',
  '                logger.info("provider_skipped_breaker", provider=name)',
  '                continue',
  '            ordered.append(provider)',
  '        return ordered',
  '',
  '    def generate_json(',
  '        self,',
  '        system_prompt: str,',
  '        user_prompt: str,',
  '        use_cache: bool = True,',
  '        temperature: float = 0.2,',
  '        max_tokens: Optional[int] = None,',
  '    ) -> Dict[str, Any]:',
  '        """Genere une reponse JSON en essayant les providers en cascade."""',
  '        # 1. Cache',
  '        cache_key = self.cache.make_key(system_prompt, user_prompt)',
  '        if use_cache:',
  '            cached = self.cache.get(cache_key)',
  '            if cached is not None:',
  '                return cached',
  '',
  '        # 2. Providers',
  '        request = AIRequest(',
  '            system_prompt=system_prompt,',
  '            user_prompt=user_prompt,',
  '            temperature=temperature,',
  '            max_tokens=max_tokens,',
  '            response_format_json=True,',
  '        )',
  '',
  '        providers = self._ordered_providers()',
  '        if not providers:',
  '            raise AIProviderError(',
  '                message="Aucun provider IA disponible (verifiez les cles API).",',
  '                details={"providers_tried": self.settings.ai_providers_list},',
  '            )',
  '',
  '        last_error: Optional[Exception] = None',
  '        for provider in providers:',
  '            try:',
  '                logger.info("provider_attempt", provider=provider.name)',
  '                response: AIResponse = provider.generate(request)',
  '                parsed = parse_json_safely(response.content)',
  '',
  '                self.breaker.record_success(provider.name)',
  '                logger.info(',
  '                    "provider_success",',
  '                    provider=provider.name,',
  '                    latency_ms=response.latency_ms,',
  '                )',
  '',
  '                if use_cache:',
  '                    self.cache.set(cache_key, parsed)',
  '',
  '                return parsed',
  '',
  '            except Exception as e:',
  '                last_error = e',
  '                self.breaker.record_failure(provider.name)',
  '                logger.warning(',
  '                    "provider_failed",',
  '                    provider=provider.name,',
  '                    error=str(e),',
  '                )',
  '                continue',
  '',
  '        raise AIProviderError(',
  '            message="Tous les providers IA ont echoue.",',
  '            details={"last_error": str(last_error) if last_error else "unknown"},',
  '        )',
  '',
  '    def available_providers(self) -> List[str]:',
  '        """Liste les noms des providers disponibles et non en pause."""',
  '        return [p.name for p in self._ordered_providers()]',
  '',
  '',
  '# Singleton',
  '_orchestrator: Optional[AIOrchestrator] = None',
  '',
  '',
  'def get_orchestrator() -> AIOrchestrator:',
  '    global _orchestrator',
  '    if _orchestrator is None:',
  '        _orchestrator = AIOrchestrator()',
  '    return _orchestrator',
]);

// ============================================================
// 14. ROUTERS — HEALTH
// ============================================================

logStep('14. Routers — health.py');

writeLines('backend/app/routers/health.py', [
  '"""Router de sante — utilise par Render.com et le monitoring."""',
  '',
  'from datetime import datetime, timezone',
  '',
  'from fastapi import APIRouter',
  '',
  'from app.core.config import get_settings',
  'from app.services.ai.orchestrator import get_orchestrator',
  '',
  'router = APIRouter(tags=["health"])',
  '',
  '',
  '@router.get("/health", summary="Verification de sante")',
  'async def health() -> dict:',
  '    """Retourne l etat de sante de l API + providers IA disponibles."""',
  '    settings = get_settings()',
  '    try:',
  '        providers = get_orchestrator().available_providers()',
  '    except Exception:',
  '        providers = []',
  '',
  '    return {',
  '        "status": "ok",',
  '        "app": settings.app_name,',
  '        "env": settings.app_env,',
  '        "version": "0.1.0",',
  '        "ai_providers_available": providers,',
  '        "timestamp": datetime.now(timezone.utc).isoformat(),',
  '    }',
  '',
  '',
  '@router.get("/", include_in_schema=False)',
  'async def root() -> dict:',
  '    return {',
  '        "message": "CandidatIA API",',
  '        "docs": "/docs",',
  '        "health": "/health",',
  '    }',
]);

// ============================================================
// 15. MAIN
// ============================================================

logStep('15. main.py');

writeLines('backend/app/main.py', [
  '"""Point d entree FastAPI de CandidatIA."""',
  '',
  'from contextlib import asynccontextmanager',
  'from typing import AsyncIterator',
  '',
  'from fastapi import FastAPI, Request',
  'from fastapi.middleware.cors import CORSMiddleware',
  'from fastapi.responses import JSONResponse',
  '',
  'from app.core.config import get_settings',
  'from app.core.errors import AppError',
  'from app.core.logging import get_logger, setup_logging',
  'from app.core.telemetry import setup_sentry',
  'from app.routers import health',
  '',
  '',
  '@asynccontextmanager',
  'async def lifespan(app: FastAPI) -> AsyncIterator[None]:',
  '    settings = get_settings()',
  '    setup_logging(settings.log_level, settings.is_production)',
  '    setup_sentry()',
  '',
  '    logger = get_logger("startup")',
  '    logger.info(',
  '        "app_starting",',
  '        app_name=settings.app_name,',
  '        env=settings.app_env,',
  '        debug=settings.app_debug,',
  '    )',
  '',
  '    yield',
  '',
  '    logger.info("app_stopping", app_name=settings.app_name)',
  '',
  '',
  'def create_app() -> FastAPI:',
  '    settings = get_settings()',
  '',
  '    app = FastAPI(',
  '        title=settings.app_name,',
  '        description=(',
  '            "API de generation de packs de candidature IA "',
  '            "(CV methode STAR + Lettre + Guide d entretien + Relance)."',
  '        ),',
  '        version="0.1.0",',
  '        docs_url="/docs" if not settings.is_production else None,',
  '        redoc_url="/redoc" if not settings.is_production else None,',
  '        openapi_url="/openapi.json" if not settings.is_production else None,',
  '        lifespan=lifespan,',
  '    )',
  '',
  '    # CORS',
  '    app.add_middleware(',
  '        CORSMiddleware,',
  '        allow_origins=[settings.frontend_url],',
  '        allow_credentials=True,',
  '        allow_methods=["*"],',
  '        allow_headers=["*"],',
  '        expose_headers=["*"],',
  '    )',
  '',
  '    # Handlers d erreurs',
  '    @app.exception_handler(AppError)',
  '    async def app_error_handler(request: Request, exc: AppError) -> JSONResponse:',
  '        logger = get_logger("error")',
  '        logger.warning(',
  '            "app_error",',
  '            error_code=exc.error_code,',
  '            message=exc.message,',
  '            path=str(request.url),',
  '            details=exc.details,',
  '        )',
  '        return JSONResponse(status_code=exc.status_code, content=exc.to_dict())',
  '',
  '    @app.exception_handler(Exception)',
  '    async def generic_error_handler(request: Request, exc: Exception) -> JSONResponse:',
  '        logger = get_logger("error")',
  '        logger.exception(',
  '            "unhandled_error",',
  '            path=str(request.url),',
  '            error=str(exc),',
  '        )',
  '        return JSONResponse(',
  '            status_code=500,',
  '            content={',
  '                "error_code": "INTERNAL_ERROR",',
  '                "message": "Une erreur interne est survenue.",',
  '                "details": {},',
  '            },',
  '        )',
  '',
  '    # Routers',
  '    app.include_router(health.router)',
  '',
  '    return app',
  '',
  '',
  'app = create_app()',
]);

// ============================================================
// 16. TESTS
// ============================================================

logStep('16. Tests unitaires');

writeLines('backend/tests/conftest.py', [
  '"""Configuration pytest partagee."""',
  '',
  'import os',
  '',
  'import pytest',
  'from fastapi.testclient import TestClient',
  '',
  'os.environ.setdefault("SECRET_KEY", "test-secret-key-for-pytest-only-32chars")',
  '',
  '',
  '@pytest.fixture(scope="session")',
  'def client() -> TestClient:',
  '    from app.main import app',
  '    return TestClient(app)',
]);

writeLines('backend/tests/test_health.py', [
  '"""Tests du router de sante."""',
  '',
  'from fastapi.testclient import TestClient',
  '',
  '',
  'def test_health_returns_ok(client: TestClient) -> None:',
  '    response = client.get("/health")',
  '    assert response.status_code == 200',
  '',
  '    data = response.json()',
  '    assert data["status"] == "ok"',
  '    assert data["app"] == "CandidatIA"',
  '    assert "timestamp" in data',
  '',
  '',
  'def test_root_returns_message(client: TestClient) -> None:',
  '    response = client.get("/")',
  '    assert response.status_code == 200',
  '    data = response.json()',
  '    assert data["message"] == "CandidatIA API"',
]);

writeLines('backend/tests/test_config.py', [
  '"""Tests de la configuration."""',
  '',
  'import pytest',
  '',
  'from app.core.config import Settings',
  '',
  '',
  'def test_settings_loads_with_minimal_env() -> None:',
  '    settings = Settings(secret_key="a" * 32)  # type: ignore[call-arg]',
  '    assert settings.app_name == "CandidatIA"',
  '    assert settings.is_development is True',
  '    assert settings.is_production is False',
  '',
  '',
  'def test_ai_providers_list_parsing() -> None:',
  '    settings = Settings(',
  '        secret_key="a" * 32,',
  '        ai_provider_order="groq, gemini , mistral",',
  '    )  # type: ignore[call-arg]',
  '    assert settings.ai_providers_list == ["groq", "gemini", "mistral"]',
  '',
  '',
  'def test_secret_key_too_short_raises() -> None:',
  '    with pytest.raises(Exception):',
  '        Settings(secret_key="short")  # type: ignore[call-arg]',
]);

writeLines('backend/tests/test_json_repair.py', [
  '"""Tests du module de reparation JSON."""',
  '',
  'import pytest',
  '',
  'from app.core.errors import AIProviderError',
  'from app.services.ai.json_repair import parse_json_safely',
  '',
  '',
  'def test_parse_simple_json() -> None:',
  '    result = parse_json_safely(\'{"a": 1, "b": 2}\')',
  '    assert result == {"a": 1, "b": 2}',
  '',
  '',
  'def test_parse_json_with_markdown_fences() -> None:',
  '    raw = "```json\\n{\\"a\\": 1}\\n```"',
  '    result = parse_json_safely(raw)',
  '    assert result == {"a": 1}',
  '',
  '',
  'def test_parse_truncated_json_repairs() -> None:',
  '    raw = \'{"a": 1, "b": [1, 2, 3\'',
  '    result = parse_json_safely(raw)',
  '    assert result["a"] == 1',
  '    assert result["b"] == [1, 2, 3]',
  '',
  '',
  'def test_parse_empty_raises() -> None:',
  '    with pytest.raises(AIProviderError):',
  '        parse_json_safely("")',
  '',
  '',
  'def test_parse_invalid_raises() -> None:',
  '    with pytest.raises(AIProviderError):',
  '        parse_json_safely("not a json at all")',
]);

writeLines('backend/tests/test_orchestrator.py', [
  '"""Tests de l orchestrateur IA (avec providers mockes)."""',
  '',
  'from unittest.mock import patch',
  '',
  'import pytest',
  '',
  'from app.core.errors import AIProviderError',
  'from app.services.ai.schemas import AIResponse',
  '',
  '',
  '@pytest.fixture',
  'def orchestrator():',
  '    with patch("app.services.ai.groq.GroqProvider.is_available", return_value=True), \\',
  '         patch("app.services.ai.gemini.GeminiProvider.is_available", return_value=False), \\',
  '         patch("app.services.ai.mistral.MistralProvider.is_available", return_value=False), \\',
  '         patch("app.services.ai.cohere.CohereProvider.is_available", return_value=False):',
  '        from app.services.ai.orchestrator import AIOrchestrator',
  '        return AIOrchestrator()',
  '',
  '',
  'def test_orchestrator_returns_parsed_json(orchestrator) -> None:',
  '    fake_response = AIResponse(',
  '        content=\'{"result": "ok"}\',',
  '        provider="groq",',
  '        model="llama-3.3-70b",',
  '        latency_ms=100,',
  '    )',
  '    with patch.object(',
  '        orchestrator._providers["groq"], "generate", return_value=fake_response',
  '    ):',
  '        result = orchestrator.generate_json("sys", "user", use_cache=False)',
  '        assert result == {"result": "ok"}',
  '',
  '',
  'def test_orchestrator_falls_back_on_failure(orchestrator) -> None:',
  '    with patch("app.services.ai.gemini.GeminiProvider.is_available", return_value=True):',
  '        orchestrator._providers["gemini"].is_available = lambda: True',
  '',
  '        def groq_fail(_req):',
  '            raise AIProviderError("groq down")',
  '',
  '        fake_response = AIResponse(',
  '            content=\'{"result": "from gemini"}\',',
  '            provider="gemini",',
  '            model="gemini-1.5-flash",',
  '            latency_ms=200,',
  '        )',
  '',
  '        with patch.object(',
  '            orchestrator._providers["groq"], "generate", side_effect=groq_fail',
  '        ), patch.object(',
  '            orchestrator._providers["gemini"], "generate", return_value=fake_response',
  '        ):',
  '            result = orchestrator.generate_json("sys", "user", use_cache=False)',
  '            assert result == {"result": "from gemini"}',
  '',
  '',
  'def test_orchestrator_raises_if_all_fail(orchestrator) -> None:',
  '    def always_fail(_req):',
  '        raise AIProviderError("fail")',
  '',
  '    with patch.object(',
  '        orchestrator._providers["groq"], "generate", side_effect=always_fail',
  '    ):',
  '        with pytest.raises(AIProviderError):',
  '            orchestrator.generate_json("sys", "user", use_cache=False)',
]);

// ============================================================
// 17. GIT COMMIT
// ============================================================

logStep('17. Commit Git');

try {
  execSync('git add .', { cwd: ROOT, stdio: 'ignore' });
  execSync('git commit -m "feat: Phase 1 - Moteur IA multi-provider avec fallback et circuit breaker"', {
    cwd: ROOT,
    stdio: 'ignore',
  });
  console.log('  OK  Commit Git effectue');
} catch (e) {
  console.log('  WARN  Git non disponible ou rien a commit (ignore)');
}

// ============================================================
// RÉSUMÉ
// ============================================================

logHeader('Phase 1 terminee avec succes');

console.log('  Fichiers crees :');
console.log('    - backend/app/core/config.py');
console.log('    - backend/app/core/errors.py');
console.log('    - backend/app/core/logging.py');
console.log('    - backend/app/core/telemetry.py');
console.log('    - backend/app/services/ai/schemas.py');
console.log('    - backend/app/services/ai/base.py');
console.log('    - backend/app/services/ai/groq.py');
console.log('    - backend/app/services/ai/gemini.py');
console.log('    - backend/app/services/ai/mistral.py');
console.log('    - backend/app/services/ai/cohere.py');
console.log('    - backend/app/services/ai/json_repair.py');
console.log('    - backend/app/services/ai/cache.py');
console.log('    - backend/app/services/ai/orchestrator.py');
console.log('    - backend/app/routers/health.py');
console.log('    - backend/app/main.py');
console.log('    - backend/tests/conftest.py');
console.log('    - backend/tests/test_health.py');
console.log('    - backend/tests/test_config.py');
console.log('    - backend/tests/test_json_repair.py');
console.log('    - backend/tests/test_orchestrator.py');
console.log('');
console.log('  Validation Phase 1 :');
console.log('');
console.log('  1. Configurer les cles API :');
console.log('     copy backend\\.env.example backend\\.env');
console.log('     # editer backend\\.env et renseigner SECRET_KEY + cles IA');
console.log('');
console.log('  2. Tester avec Docker :');
console.log('     docker-compose up --build');
console.log('');
console.log('     Puis ouvrir :');
console.log('       http://localhost:8000/health');
console.log('       http://localhost:8000/docs');
console.log('');
console.log('  3. OU tester sans Docker :');
console.log('     cd backend');
console.log('     python -m venv venv');
console.log('     .\\venv\\Scripts\\Activate.ps1');
console.log('     pip install -r requirements.txt');
console.log('     pytest');
console.log('');
console.log('  Prochaine etape : Phase 2 (Ingestion multi-format)');
console.log('');